name: reviewdog
on: [pull_request]
jobs:
  eslint-added:
    name: runner / eslint-added
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          eslint_flags: "plugins/**/*.js"
          fail_on_error: true
          filter_mode: added
